build: importation du theme Keycloak dans le projet
DNUM-SocialGouv/c2s pull request #122
Opened 2024-11-12 12:40 UTC by SylvainBlancheDNUM

J'ai importé la branche "main" du projet c2s-keycloak-theme.

2024-11-13 11:40 UTC, SamiTliliDNUM requested changes
A discuter

2024-11-14 08:09 UTC, SylvainBlancheDNUM commented
Oui sur quels sujets ?

2024-11-15 11:06 UTC, SylvainBlancheDNUM commented
@SamiTliliDNUM J'ai regardé pour le sujet des informations sensibles, je n'ai rien trouvé dans le thème.
@olivier-rabot si tu peux faire une passe rapide, sinon je pense que c'est bon.

(En passant j'ai vu qu'on chargeait un fichier tailwind depuis un cdn)

2024-11-15 11:16 UTC, SamiTliliDNUM approved these changes

2024-11-20 13:37 UTC, closed without merging